### ISSUE TITLE
Please Respect The Original Project And Credit The Owner!

### ISSUE THREAD

**Issue by ngntriminh** [kumaresankp/ResumeGrabber#1]
Hello, I'm the owner of the project. It's great to see you're sharing my project but please give me a credit. I see you re-uploaded my source code without crediting me and you changed my GitHub username into yours, which is not respectful. You even replaced my "Buy Me A Coffee" link with your link, so please stop taking advantage from me. You can fork my original repo if you want to contribute something. If you don't credit me (by adding my original repo and deleting your repo) or take your repo and [this](https://www.youtube.com/watch?v=10FeDzfU4bg) video down, I will have to report them. Thank you! My original project is here: https://github.com/ngntriminh/ResumeGrabber.

**Comment by ngntriminh** [comment]
You have 1 week to take your repo and your video down. Or I will do it for you, I said politely before but it looks like you're still trying to steal my project. OK fine, be ready to receive my report! I will take this seriously.

**Comment by kumaresankp** [comment]
.
